#!/bin/bash
# Terraform Workspace Manager
# Enterprise-grade workspace management for multi-environment deployments

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
ENVIRONMENTS=("dev" "staging" "prod")
DEFAULT_WORKSPACE="dev"

print_banner() {
    echo -e "${BLUE}"
    echo "=================================================================="
    echo "🏢 TERRAFORM WORKSPACE MANAGER"
    echo "=================================================================="
    echo "Enterprise workspace management for multi-environment deployments"
    echo "=================================================================="
    echo -e "${NC}"
}

list_workspaces() {
    echo -e "${YELLOW}📋 Available Terraform Workspaces:${NC}"
    terraform workspace list
    
    echo -e "${BLUE}📊 Current workspace:${NC}"
    terraform workspace show
}

create_workspace() {
    local workspace="$1"
    
    echo -e "${YELLOW}🏗️  Creating workspace: $workspace${NC}"
    
    if terraform workspace new "$workspace"; then
        echo -e "${GREEN}✅ Workspace '$workspace' created successfully${NC}"
        
        # Create workspace-specific variables file
        local vars_file="terraform.tfvars.$workspace"
        if [ ! -f "$vars_file" ]; then
            cat > "$vars_file" << EOF
# Terraform variables for $workspace environment
# Generated by workspace manager

# Environment-specific configuration
environment = "$workspace"
location = "eastus"

# Resource naming
resource_prefix = "zt-iot-$workspace"

# Environment-specific settings
sku_tier = "$([ "$workspace" = "prod" ] && echo "Standard" || echo "Free")"
replica_count = $([ "$workspace" = "prod" ] && echo "3" || echo "1")

# Tags
tags = {
  Environment = "$workspace"
  Project     = "zero-trust-iot"
  ManagedBy   = "terraform"
  Workspace   = "$workspace"
}
EOF
            echo -e "${GREEN}✅ Created variables file: $vars_file${NC}"
        fi
        
    else
        echo -e "${RED}❌ Failed to create workspace: $workspace${NC}"
        return 1
    fi
}

select_workspace() {
    local workspace="$1"
    
    echo -e "${YELLOW}🔄 Switching to workspace: $workspace${NC}"
    
    if terraform workspace select "$workspace"; then
        echo -e "${GREEN}✅ Switched to workspace: $workspace${NC}"
        
        # Show workspace info
        echo -e "${BLUE}📊 Workspace information:${NC}"
        echo "  • Name: $(terraform workspace show)"
        echo "  • State key: $workspace/terraform.tfstate"
        
        # Check for workspace-specific variables
        local vars_file="terraform.tfvars.$workspace"
        if [ -f "$vars_file" ]; then
            echo "  • Variables file: $vars_file"
        else
            echo -e "  ${YELLOW}⚠️  No workspace-specific variables file found${NC}"
        fi
        
        # Show resource count
        local resource_count=$(terraform state list 2>/dev/null | wc -l || echo "0")
        echo "  • Resources: $resource_count"
        
    else
        echo -e "${RED}❌ Failed to switch to workspace: $workspace${NC}"
        return 1
    fi
}

delete_workspace() {
    local workspace="$1"
    
    if [ "$workspace" = "default" ]; then
        echo -e "${RED}❌ Cannot delete the default workspace${NC}"
        return 1
    fi
    
    echo -e "${YELLOW}🗑️  Preparing to delete workspace: $workspace${NC}"
    
    # Switch away from workspace if currently selected
    if [ "$(terraform workspace show)" = "$workspace" ]; then
        terraform workspace select default
        echo -e "${BLUE}📍 Switched to default workspace${NC}"
    fi
    
    # Check if workspace has resources
    terraform workspace select "$workspace"
    local resource_count=$(terraform state list 2>/dev/null | wc -l || echo "0")
    terraform workspace select default
    
    if [ "$resource_count" -gt 0 ]; then
        echo -e "${RED}⚠️  Workspace '$workspace' contains $resource_count resources${NC}"
        read -p "Are you sure you want to delete it? (yes/no): " confirm
        if [ "$confirm" != "yes" ]; then
            echo -e "${YELLOW}❌ Workspace deletion cancelled${NC}"
            return 1
        fi
    fi
    
    # Delete workspace
    if terraform workspace delete "$workspace"; then
        echo -e "${GREEN}✅ Workspace '$workspace' deleted successfully${NC}"
        
        # Remove workspace-specific files
        local vars_file="terraform.tfvars.$workspace"
        if [ -f "$vars_file" ]; then
            rm "$vars_file"
            echo -e "${GREEN}✅ Removed variables file: $vars_file${NC}"
        fi
        
    else
        echo -e "${RED}❌ Failed to delete workspace: $workspace${NC}"
        return 1
    fi
}

plan_workspace() {
    local workspace="$1"
    
    echo -e "${YELLOW}📋 Planning deployment for workspace: $workspace${NC}"
    
    # Switch to workspace
    terraform workspace select "$workspace"
    
    # Use workspace-specific variables if available
    local vars_file="terraform.tfvars.$workspace"
    local vars_args=""
    if [ -f "$vars_file" ]; then
        vars_args="-var-file=$vars_file"
        echo -e "${BLUE}📁 Using variables file: $vars_file${NC}"
    fi
    
    # Create plan with workspace-specific name
    local plan_file="tfplan-$workspace"
    
    if terraform plan $vars_args -out="$plan_file"; then
        echo -e "${GREEN}✅ Plan created: $plan_file${NC}"
        
        # Show plan summary
        terraform show -json "$plan_file" | jq -r '
            .resource_changes[] |
            select(.change.actions != ["no-op"]) |
            "\(.address): \(.change.actions | join(", "))"'
            
    else
        echo -e "${RED}❌ Planning failed for workspace: $workspace${NC}"
        return 1
    fi
}

apply_workspace() {
    local workspace="$1"
    local plan_file="tfplan-$workspace"
    
    echo -e "${YELLOW}🚀 Applying changes to workspace: $workspace${NC}"
    
    # Check if plan exists
    if [ ! -f "$plan_file" ]; then
        echo -e "${RED}❌ No plan file found: $plan_file${NC}"
        echo "Run 'plan' command first"
        return 1
    fi
    
    # Switch to workspace
    terraform workspace select "$workspace"
    
    # Apply the plan
    if terraform apply "$plan_file"; then
        echo -e "${GREEN}✅ Successfully applied changes to workspace: $workspace${NC}"
        
        # Clean up plan file
        rm "$plan_file"
        echo -e "${BLUE}🧹 Cleaned up plan file${NC}"
        
        # Show final resource count
        local resource_count=$(terraform state list | wc -l)
        echo -e "${BLUE}📊 Total resources in workspace: $resource_count${NC}"
        
    else
        echo -e "${RED}❌ Apply failed for workspace: $workspace${NC}"
        return 1
    fi
}

destroy_workspace() {
    local workspace="$1"
    
    echo -e "${RED}💥 Destroying all resources in workspace: $workspace${NC}"
    
    # Switch to workspace
    terraform workspace select "$workspace"
    
    # Show what will be destroyed
    echo -e "${YELLOW}📋 Resources to be destroyed:${NC}"
    terraform state list
    
    # Confirm destruction
    read -p "Are you sure you want to destroy ALL resources in '$workspace'? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        echo -e "${YELLOW}❌ Destruction cancelled${NC}"
        return 1
    fi
    
    # Use workspace-specific variables if available
    local vars_file="terraform.tfvars.$workspace"
    local vars_args=""
    if [ -f "$vars_file" ]; then
        vars_args="-var-file=$vars_file"
    fi
    
    # Destroy resources
    if terraform destroy $vars_args -auto-approve; then
        echo -e "${GREEN}✅ All resources destroyed in workspace: $workspace${NC}"
    else
        echo -e "${RED}❌ Destruction failed for workspace: $workspace${NC}"
        return 1
    fi
}

compare_workspaces() {
    local workspace1="$1"
    local workspace2="$2"
    
    echo -e "${YELLOW}🔍 Comparing workspaces: $workspace1 vs $workspace2${NC}"
    
    # Get resource lists for both workspaces
    terraform workspace select "$workspace1"
    local resources1=$(terraform state list 2>/dev/null | sort || echo "")
    
    terraform workspace select "$workspace2"
    local resources2=$(terraform state list 2>/dev/null | sort || echo "")
    
    # Compare resource counts
    local count1=$(echo "$resources1" | wc -l)
    local count2=$(echo "$resources2" | wc -l)
    
    echo -e "${BLUE}📊 Resource comparison:${NC}"
    echo "  • $workspace1: $count1 resources"
    echo "  • $workspace2: $count2 resources"
    
    # Find differences
    echo -e "${BLUE}🔍 Resource differences:${NC}"
    
    # Resources only in workspace1
    local only_in_1=$(comm -23 <(echo "$resources1") <(echo "$resources2"))
    if [ -n "$only_in_1" ]; then
        echo -e "${YELLOW}  Only in $workspace1:${NC}"
        echo "$only_in_1" | sed 's/^/    /'
    fi
    
    # Resources only in workspace2
    local only_in_2=$(comm -13 <(echo "$resources1") <(echo "$resources2"))
    if [ -n "$only_in_2" ]; then
        echo -e "${YELLOW}  Only in $workspace2:${NC}"
        echo "$only_in_2" | sed 's/^/    /'
    fi
    
    # Common resources
    local common=$(comm -12 <(echo "$resources1") <(echo "$resources2"))
    if [ -n "$common" ]; then
        local common_count=$(echo "$common" | wc -l)
        echo -e "${GREEN}  Common resources: $common_count${NC}"
    fi
}

setup_environments() {
    echo -e "${YELLOW}🏗️  Setting up standard environments...${NC}"
    
    for env in "${ENVIRONMENTS[@]}"; do
        echo -e "${BLUE}Setting up environment: $env${NC}"
        
        # Create workspace if it doesn't exist
        if ! terraform workspace select "$env" 2>/dev/null; then
            create_workspace "$env"
        else
            echo -e "${GREEN}✅ Workspace '$env' already exists${NC}"
        fi
    done
    
    # Switch back to default workspace
    terraform workspace select "$DEFAULT_WORKSPACE"
    echo -e "${GREEN}✅ Environment setup complete${NC}"
}

usage() {
    echo "Terraform Workspace Manager"
    echo ""
    echo "Usage: $0 <command> [arguments]"
    echo ""
    echo "Commands:"
    echo "  list                    - List all workspaces"
    echo "  create <name>           - Create new workspace"
    echo "  select <name>           - Switch to workspace"
    echo "  delete <name>           - Delete workspace"
    echo "  plan <name>             - Plan deployment for workspace"
    echo "  apply <name>            - Apply planned changes"
    echo "  destroy <name>          - Destroy all resources in workspace"
    echo "  compare <ws1> <ws2>     - Compare two workspaces"
    echo "  setup                   - Set up standard environments"
    echo "  help                    - Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 create dev           # Create development workspace"
    echo "  $0 select prod          # Switch to production workspace"
    echo "  $0 plan staging         # Plan staging deployment"
    echo "  $0 compare dev prod     # Compare dev and prod workspaces"
}

main() {
    case "${1:-}" in
        "list")
            list_workspaces
            ;;
        "create")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 create <workspace_name>"
                exit 1
            fi
            create_workspace "$2"
            ;;
        "select")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 select <workspace_name>"
                exit 1
            fi
            select_workspace "$2"
            ;;
        "delete")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 delete <workspace_name>"
                exit 1
            fi
            delete_workspace "$2"
            ;;
        "plan")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 plan <workspace_name>"
                exit 1
            fi
            plan_workspace "$2"
            ;;
        "apply")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 apply <workspace_name>"
                exit 1
            fi
            apply_workspace "$2"
            ;;
        "destroy")
            if [ $# -lt 2 ]; then
                echo -e "${RED}❌ Workspace name required${NC}"
                echo "Usage: $0 destroy <workspace_name>"
                exit 1
            fi
            destroy_workspace "$2"
            ;;
        "compare")
            if [ $# -lt 3 ]; then
                echo -e "${RED}❌ Two workspace names required${NC}"
                echo "Usage: $0 compare <workspace1> <workspace2>"
                exit 1
            fi
            compare_workspaces "$2" "$3"
            ;;
        "setup")
            setup_environments
            ;;
        "help"|"--help"|"-h"|"")
            print_banner
            usage
            ;;
        *)
            echo -e "${RED}❌ Unknown command: $1${NC}"
            usage
            exit 1
            ;;
    esac
}

main "$@"